version: '2.2'

services:

  # influxdb:
  #   container_name: influxdb
  #   image: influxdb:1.0.2
  #   ports:
  #     - "8083:8083"
  #     - "8086:8086"
  #   volumes:
  #     - ./influxdb:/var/lib/influxdb:rw
  #   restart: always
  #   networks:
  #     - backend
 
  # telegraf:
  #   container_name: telegraf
  #   image: telegraf:1.3.3
  #   # network_mode: "host"
  #   volumes:
  #     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: always
  #   links:
  #     - influxdb
  #   networks:
  #     - backend

  # fluentd:
  #   build: ./fluentd
  #   container_name: fluentd
  #   links:
  #     - influxdb
  #   depends_on:
  #     influxdb:
  #       condition: service_healthy
  #   ports:
  #     - 24224:24224
  #   networks:
  #     - backend

  web:
    image: nginx:mainline-alpine
    restart: always
    mem_limit: 32m
    ports:
      - "8080:80"
      - "8088:443"
    volumes:
      - ./app/sitescomemorativos:/app:rw
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    logging:
      driver: journald
    # links:
      # - telegraf

  php:
    build: ./php
    mem_limit: 64m
    restart: always
    ports:
      - "9000"
    volumes:
      - ./app/sitescomemorativos:/app
    tmpfs: /var/cache
    tty: true
    networks:
      - backend
    command: sh -c 'chown -R www-data:www-data /app && exec php-fpm'
    # links:
      # - telegraf
    logging:
      driver: journald
      
        

  db:
    container_name: mariadb
    image: mysql:5.7.21
#    build: ./db
    mem_limit: 128m
    ports:
      - "3360:3306"
    volumes:
      - ./db/my.cnf:/etc/mysql/my.cnf:ro
      - ./db/data:/var/lib/mysql:rw,delegated
    environment:
      - MYSQL_DATABASE=sc_app_db
      - MYSQL_USER=sc_app_user
      - MYSQL_PASSWORD=sc123456
      - MYSQL_ROOT_PASSWORD=sc123456
      - MYSQL_ROOT_HOST=127.0.0.1
    restart: always
    networks:
      - backend
    # links:
      # - telegraf
    logging:
      driver: journald


      

networks:
  backend:
