version: '2.2'

services:

  influxdb:
    image: tutum/influxdb
    container_name: influxdb
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      - PRE_CREATE_DB=vm_metrics
    networks:
      - backend

  # fluentd:
  #   build: ./fluentd
  #   container_name: fluentd
  #   links:
  #     - influxdb
  #   depends_on:
  #     influxdb:
  #       condition: service_healthy
  #   ports:
  #     - 24224:24224
  #   networks:
  #     - backend

  telegraf:
    container_name: telegraf
    image: telegraf:1.3.3
    #network_mode: "host"
    depends_on:
      influxdb:
        condition: service_healthy
    links:
        - influxdb
    environment:
        HOST_NAME: "telegraf"
        INFLUXDB_HOST: "influxdb"
        INFLUXDB_PORT: "8086"
        DATABASE: "vm_metrics"
    tty: true
    privileged: true
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - backend

  web:
    image: nginx:mainline-alpine
    restart: always
    mem_limit: 32m
    ports:
      - "8080:80"
      - "8088:443"
    volumes:
      - ./app/sitescomemorativos:/app:rw
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    links:
      - telegraf

  php:
    build: ./php
    mem_limit: 64m
    restart: always
    ports:
      - "9000"
    volumes:
      - ./app/sitescomemorativos:/app
    tmpfs: /var/cache
    tty: true
    networks:
      - backend
    command: sh -c 'chown -R www-data:www-data /app && exec php-fpm'
    links:
      - telegraf

      
        

  db:
    container_name: mariadb
    image: mysql:5.7.21
#    build: ./db
    mem_limit: 128m
    ports:
      - "3360:3306"
    volumes:
      - ./db/my.cnf:/etc/mysql/my.cnf:ro
      - ./db/data:/var/lib/mysql:rw,delegated
    environment:
      - MYSQL_DATABASE=sc_app_db
      - MYSQL_USER=sc_app_user
      - MYSQL_PASSWORD=sc123456
      - MYSQL_ROOT_PASSWORD=sc123456
      - MYSQL_ROOT_HOST=127.0.0.1
    restart: always
    networks:
      - backend
    links:
      - telegraf


      

networks:
  backend:
